region_pbf : [
  "https://download.geofabrik.de/europe/italy/centro-latest.osm.pbf",
  "https://download.geofabrik.de/europe/italy/isole-latest.osm.pbf",
  "https://download.geofabrik.de/europe/italy/nord-est-latest.osm.pbf",
  "https://download.geofabrik.de/europe/italy/nord-ovest-latest.osm.pbf",
  "https://download.geofabrik.de/europe/italy/sud-latest.osm.pbf"
]
collection:
  osm_tags:
    amenity: ["atm", "bank", "bar", "biergarten", "bicycle_parking", "bicycle_rental", "bus_station", "cafe", "car_sharing", "charging_station",
              "cinema", "dentist", "doctors", "fast_food", "fuel", "ice_cream", "kneipp_water_cure", "library",
              "marketplace", "nightclub", "pharmacy", "place_of_worship", "planetarium", "post_box", "post_office", "parking", "pub",
              "recycling", "restaurant", "taxi", "theatre", "vending_machine","police", "townhall","community_centre","department_store"]
    shop: ["bakery", "butcher", "chemist", "clothes", "convenience", "deli", "farm", "fashion", "florist", "fuel", "general",
           "greengrocer", "grocery", "hairdresser", "health_food", "honey", "kiosk", "mall", "shoes", "sports",
           "supermarket", "wine","books"]
    tourism: ["alpine_hut", "apartment", "aquarium", "camp_site", "caravan_site", "chalet", "gallery", "guest_house",
               "hostel", "hotel", "motel", "museum", "theme_park", "zoo"]
    railway: ["platform", "station", "stop", "subway_entrance", "tram_stop"]
    leisure: ["amusement_arcade", "disc_golf_course", "dog_park", "escape_game", "fitness_centre", "fitness_station",
              "miniature_golf", "playground", "sports_centre", "sports_hall", "swimming_area", "water_park","swimmning_pool"]
    sport: ["fitness", "swimming", "yoga"]
    highway: ["bus_stop"]
    public_transport: ["station", "stop_position"]
    historic: ["aircraft", "aqueduct", "archaeological_site", "battlefield", "bomb_crater", "castle", "church",
               "city_gate", "citywalls", "fort", "locomotive", "memorial", "monastery", "monument",
               "railway_car", "ruins", "ship", "tank", "tomb", "tower", "vehicle", "wreck"]
    building: ["public", "townhall"]
  additional_columns: ["name", "operator", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "email", "website", 
                       "capacity", "opening_hours", "wheelchair", "origin", "organic", "subway", "brand", "indoor", "outdoor"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  supermarket:
    classify_by_name:
      convenience: 
        children:
          carrefour_brand : ["carrefour express"]
          conad_brand : ["margherita conad"]
          a&o_brand: ["spesa a&o"]
          despart_brand: ["despar express",]
        threshold: 1
    
      supermarket: 
        children:
          basko : ["basko"]
          carrefour : ["carrefour", "carrefour express", "carrefour market"]
          conad : ["conad", "conad city", "connad superstore"]
          coop: ["coop", "incoop", "coop superstore", "coop&coop", "coop.fi"]
          crai: ["crai"]
          despar: ["despar"]
          esselunga: ["esselunga"]
          famila: ["famila"]
          il gigante: ["il gigante"]
          pam: ["pam"]
          sigma: ["sigma"]
          unes: ["unes"]
          a&o: ["a&o"]
        threshold: 0.7

      discount_supermarket: 
        children:
          aldi : ["aldi"]
          lidl : ["lidl"]
          eurospin : ["eurospin"]
          mercato : ["mercato"]
          md : ["md"]
          penny : ["penny"]
          dico : ["dico"]
          in's mercato : ["in's mercato"]
          dpiù : ["dpiù"]
          todis : ["todis"]
          prix quality : ["prix quality"]
          sosty : ["sosty"]
          ard : ["ard"]
          tuodì : ["tuodì"]
        threshold: 0.8

      hypermarket: 
        children:
          bennet : ["bennet"]
          ipermercato carrefour : ["ipermercato carrefour"]
          ipercoop : ["ipercoop"]
          esselunga superstore : ["esselunga superstore"]
          spazio conad : ["spazio conad"]
          ipercoop : ["extracoop", "ipercoop"]
          interspar : ["interspar"]
          il gigante : ["il gigante"]
          conad superstore : ["conad superstore"]
          familia superstore : ["familia superstore"]
          pam panorama : ["pam panorama", "panorama"]
          iper : ["iper"]
        threshold: 0.9
      
      organic_supermarket:
        children:
          naturasi : ["naturasi"]
          biosapori : ["biosapori"]
        threshold: 0.7
      
      chemist: 
        children:
          acqua e sapone : ["acqua e sapone", "acqua & sapone"]
          tigotà: ["tigotà"]
          promotre : ["promotre"]
          dm : ["dm"]
        threshold: 0.7

      other_grocery:
        children:
          turco : ["turco", "turkish", "turk"]
          asia : ["asia", "asiatico", "asian"]
          other : ["italiano", "polacco", "spagnolo", "russo"]
        threshold: 0.7

    classify_by_tag:
      other_grocery:
        origin: [True] 
      organic_supermarket:
        organic: ["only"]
      discount_supermarket: 
        name: ["np"]
      supermarket:
        name: ["combi"]
      chemist:
        name: ["dm"]
    unmatched: "other_grocery"

  convenience:
    classify_by_tag:
      other_grocery:
        shop: ["convenience"]

  deli:
    classify_by_tag:
      other_grocery:
        shop: ["deli"]
      
  greengrocer:
    classify_by_tag:
      other_grocery: 
        shop: ["greengrocer"]

  health_food: 
    classify_by_tag:
      organic_supermarket:
        shop: ["health_food"]

  chemist:
    classify_by_tag:
      chemist:
        shop: ["chemist"]

  convenience: 
    inherit: "supermarket"
  grocery: 
    inherit: "supermarket"
  deli: 
    inherit: "supermarket"


subscription:
  repo_url: "https://github.com/plan4better/pois"
    