region_pbf : [
    "https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" , 
    "https://download.geofabrik.de/europe/germany/rheinland-pfalz-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/bayern-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/schleswig-holstein-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf"
]
collection:
  osm_tags:
    amenity: ["atm", "bank", "bar", "biergarten", "bicycle_parking", "bicycle_rental", "bus_station", "cafe", "car_sharing", "charging_station",
              "cinema", "dentist", "doctors", "fast_food", "fuel", "ice_cream", "kneipp_water_cure", "library",
              "marketplace", "nightclub", "pharmacy", "place_of_worship", "planetarium", "post_box", "post_office", "parking", "pub",
              "recycling", "restaurant", "taxi", "theatre", "vending_machine","police", "townhall","community_centre","department_store"]
    shop: ["bakery", "butcher", "chemist", "clothes", "convenience", "deli", "farm", "fashion", "florist", "fuel", "general",
           "greengrocer", "grocery", "hairdresser", "health_food", "honey", "kiosk", "mall", "shoes", "sports",
           "supermarket", "wine","books"]
    tourism: ["alpine_hut", "apartment", "aquarium", "camp_site", "caravan_site", "chalet", "gallery", "guest_house",
               "hostel", "hotel", "motel", "museum", "theme_park", "zoo"]
    railway: ["platform", "station", "stop", "subway_entrance", "tram_stop"]
    leisure: ["amusement_arcade", "disc_golf_course", "dog_park", "escape_game", "fitness_centre", "fitness_station",
              "miniature_golf", "playground", "sports_centre", "sports_hall", "swimming_area", "water_park","swimmning_pool"]
    sport: ["fitness", "swimming", "yoga"]
    highway: ["bus_stop"]
    public_transport: ["station", "stop_position"]
    historic: ["aircraft", "aqueduct", "archaeological_site", "battlefield", "bomb_crater", "castle", "church",
               "city_gate", "citywalls", "fort", "locomotive", "memorial", "monastery", "monument",
               "railway_car", "ruins", "ship", "tank", "tomb", "tower", "vehicle", "wreck"]
    building: ["public", "townhall"]
  additional_columns: ["name", "operator", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "email", "website", 
                       "capacity", "opening_hours", "wheelchair", "origin", "organic", "subway", "brand", "indoor", "outdoor"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  supermarket:
    classify_by_name:
      convenience: 
        children:
          rewe_brand     : ["rewe to go","rewe express"]
          spar_brand     : ["spar express"]
          edeka_brand    : ["edeka xpress"]
          konsum_brand    : ["konsum express"]
        threshold: 0.9
      supermarket: 
        children:
          rewe     : ["rewe", "rewe city"]
          tegut    : ["tegut"]
          feneberg : ["feneberg"]
          nahkauf  : ["nahkauf"]
          kupsch   : ["kupsch"]
          aez      : ["aez"]
          edeka    : ["edeka", "nah & gut", "e center", "diska", "e aktiv"]
          k+k      : ["k+k", "k&k"]
          nah&frisch : ["nah&frisch"]
          nah&gut  : ["nah&gut", "nah und gut"]
          cap-markt : ["cap-markt"]
          markant   : ["markant"]
          konsum    : ["konsum"]
          combi     : ["combi"]
          famila    : ["famila"]
          billa     : ["billa"]
        threshold: 0.7

      discount_supermarket: 
        children:
          aldi  : ["aldi"]
          lidl  : ["lidl"]
          netto : ["netto"]
          norma : ["norma"]
          penny : ["penny"]
        threshold: 0.8

      hypermarket: 
        children:
          real      : ["real"]
          v-markt   : ["v-markt"]
          kaufland  : ["kaufland"]
          hit       : ["hit"]
          globus    : ["globus"]
          marktkauf: ["marktkauf"]
        threshold: 0.9

      wholesale: 
        children:
          metro     : ["metro"]
          hamberger : ["hamberger"]
        threshold: 0.7
      
      organic_supermarket:
        children:
          denn's Biomarkt : ["denn's", "denns", "denn"]
          alnatura : ["alnatura"]
          vollcorner : ["vollcorner"]
          reformhaus : ["reformhaus"]
          naturkost : ["naturkost"]
          bio: ["bio", "bioladen"]
          vitalia : ["vitalia"]
        threshold: 0.7
      
      chemist: 
        children:
          rossmann : ["rossmann"]
          müller : ["müller", "mueller"]
          drogerie: ["drogerie"]
        threshold: 0.7
      
      variety_store: 
        children:
          tedi : ["tedi"]
        threshold: 0.7
        
      other_grocery:
        children:
          turkish : ["türkisch", "turkish", "turk"]
          asia : ["asia", "asien", "asiatische"]
          other : ["italienisch", "polnische", "spanische", "russisch"]
          mix markt : ["mix markt"]
        threshold: 0.7

    classify_by_tag:
      other_grocery:
        origin: [True]
      organic_supermarket:
        organic: ["only"]
      discount_supermarket: 
        name: ["np"]
      supermarket:
        name: ["combi"]
      chemist:
        name: ["dm"]
    unmatched: "other_grocery"
  
  convenience:
    classify_by_tag:
      other_grocery:
        shop: ["convenience"]

  deli:
    classify_by_tag:
      other_grocery:
        shop: ["deli"]
      
  greengrocer:
    classify_by_tag:
      other_grocery: 
        shop: ["greengrocer"]

  health_food: 
    classify_by_tag:
      organic_supermarket:
        shop: ["health_food"]

  chemist:
    classify_by_tag:
      chemist:
        shop: ["chemist"]
  
  convenience: 
    inherit: "supermarket"
  grocery: 
    inherit: "supermarket"
  deli: 
    inherit: "supermarket"
  pub: 
    inherit: "bar"
  ice_cream:
    inherit: "cafe"

  

validation:
  new_poi_table: "public.poi_osm_de"
  old_poi_table:
    ["goat.poi_shopping","goat.poi_health","goat.poi_tourism_leisure","goat.poi_food_drink","goat.poi_mobility_service","goat.poi_public_service","goat.poi_service"]
  metrics:
    poi_count:
      geom_reference_query: "SELECT objektidentifikator AS id , geografischername_gen AS name, 0 as population, geom AS geom FROM public.germany_counties"
      thresholds:
        absolute:
          positive: 4
          negative: -4
        relative:
          bakery: [-0.3, 0.3]
          butcher: [-0.3, 0.3]
          chemist: [-0.3, 0.3]
          discount_supermarket: [-0.3, 0.3]
          farm_shop: [-0.3, 0.3]
          food_vending_machine: [-0.3, 0.3]
          hypermarket: [-0.3, 0.3]
          marketplace: [-0.3, 0.3]
          organic_supermarket: [-0.3, 0.3]
          other_grocery: [-0.3, 0.3]
          supermarket: [-0.3, 0.3]
          winery: [-0.3, 0.3]
          dentist: [-0.3, 0.3]
          general_practitioner: [-0.3, 0.3]
          hospital: [-0.3, 0.3]
          pharmacy: [-0.3, 0.3]
      lower_bound: 3
    # poi_density:
    #   geom_reference_query: "SELECT objektidentifikator, geografischername_gen, einwohnerzahl_ewz, geom FROM public.germany_counties"
    #   thresholds:
    #     default: 100.0
    #     supermarket: 50.0
    #     bakery: 80.0
    #     pharmacy: 60.0
    #     dentist: 30.0
    #     restaurant: 200.0
    #     hospital: 10.0
    poi_per_people:
      geom_reference_query: "SELECT objektidentifikator AS id , einwohnerzahl_ewz as population, geografischername_gen AS name, geom FROM public.germany_municipalities"
      capita_people_count: 1000
      thresholds:
        absolute:
          positive: 0.3
          negative: -0.3
        relative:
          bakery: [-0.5, 0.5]
          butcher: [-0.5, 0.5]
          chemist: [-0.5, 0.5]
          discount_supermarket: [-0.5, 0.5]
          farm_shop: [-0.5, 0.5]
          food_vending_machine: [-0.5, 0.5]
          hypermarket: [-0.5, 0.5]
          marketplace: [-0.5, 0.5]
          organic_supermarket: [-0.5, 0.5]
          other_grocery: [-0.5, 0.5]
          supermarket: [-0.5, 0.5]
          winery: [-0.5, 0.5]
        # new_emergence: 0.05
      lower_bound: 0.03
    # population_per_poi:
    #   geom_reference_query: "SELECT objektidentifikator, geografischername_gen, einwohnerzahl_ewz, geom FROM public.germany_counties"
    #   thresholds:
    #     default: 0.2
    #     restaurant: 0.1
    #     hospital: 0.05
  lcs:
    poi_columns:
    - id
    - name
    - category
    - geom
    excluded_categories: ['bus_stop', 'bus_station']
    search_radius_m: 40       # Max planar distance in meters for finding nearby POIs
    weights:
      name: 0.6          # Weight for name similarity in combined score
      category: 0.4      # Weight for category similarity in combined score
    threshold_lcs: 0.55        # Overall similarity threshold for flagging a match


subscription:
  repo_url: "https://github.com/plan4better/pois"
  merged_categories:
    sight_or_cultural_site: ['aircraft', 'aqueduct', 'archaeological_site', 'battlefield', 'bomb_crater', 'castle', 'city_gate', 'citywalls', 'farm', 'fort', 'locomotive', 'memorial', 'monument', 'railway_car', 'ruins', 'ship', 'tank', 'tomb', 'tower', 'vehicle', 'wreck', 'pier', 'lighthouse', 'obelisk', 'stupa', 'windmill', 'artwork']
    recreational_or_adventure_facility: ['amusement_arcade', 'disc_golf_course', 'dog_park', 'escape_game', 'miniature_golf', 'aquarium', 'zoo', 'theme_park']
    water_recreation_or_wellness_facility: ['swimming', 'water_park', 'kneipp_water_cure', 'public_bath', 'bathing_place']
    indoor_accommodation: ['hotel', 'alpine_hut', 'apartment','chalet', 'hostel', 'motel', 'guest_house']
    outdoor_accommodation: ['camp_site', 'caravan_site']




    